# Generated by Django 5.0.3 on 2026-01-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracktime_t_created_5d4325_idx',
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_card_deleted_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='tracktime.activitytype'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='board_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='card_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='minutes',
            field=models.PositiveIntegerField(help_text='Tempo em minutos'),
        ),
    ]
