# Generated by ChatGPT on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracktime", "0002_remove_timeentry_tracktime_t_created_5d4325_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="confirm_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="auto_stop_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="confirmation_token_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="last_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="confirm_cycle",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
