# Generated by Django 5.0.3 on 2026-02-03 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktime', '0005_alter_activitytype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ping_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tab', models.CharField(blank=True, default='', max_length=40)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
