# Generated by Django 5.0.3 on 2026-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktime', '0006_trackpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='card_title_cache',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
