# Generated by Django 5.2.17 on 2026-09-21 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktime', '0007_alter_timeentry_card_title_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracktime_t_user_id_9c5761_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='tracktime_t_card_id_ff58f4_idx',
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['board_id', 'ended_at'], name='te_board_ended_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['card_id', 'ended_at'], name='te_card_ended_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'ended_at'], name='te_user_ended_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['created_at'], name='te_created_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['auto_stop_at'], name='te_autostop_open_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['confirm_due_at'], name='te_confirmdue_open_idx'),
        ),
    ]
