# Generated by Django 5.0.3 on 2025-11-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_attachment_card_tags_alter_card_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position']},
        ),
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='boards.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
