# Generated by Django 5.0.3 on 2025-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_card_options_card_deleted_at_card_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_covers/'),
        ),
        migrations.AddField(
            model_name='column',
            name='theme',
            field=models.CharField(choices=[('gray', 'Cinza'), ('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo'), ('amber', 'Bege')], default='gray', max_length=20),
        ),
    ]
