# Generated by Django 5.0.3 on 2025-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_board_image_column_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_backgrounds/'),
        ),
        migrations.AddField(
            model_name='board',
            name='background_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='theme',
            field=models.CharField(choices=[('gray', 'Cinza'), ('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo'), ('amber', 'Bege'), ('red', 'Vermelho'), ('pink', 'Rosa'), ('teal', 'Verde-água'), ('indigo', 'Índigo')], default='gray', max_length=20),
        ),
    ]
