# Generated by Django 5.0.3 on 2025-11-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_board_background_image_board_background_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attachment',
        ),
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
