# Generated by Django 5.0.3 on 2025-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_checklistitem_options_checklistitem_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
