# Generated by Django 5.0.3 on 2025-11-22 22:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_column_deleted_at_column_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
