# Generated by Django 5.0.3 on 2025-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_board_created_by_alter_board_created_at_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='home_wallpaper_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
