# Generated by Django 5.0.3 on 2025-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_alter_board_created_at'),
        ('boards', '0013_board_created_by_alter_board_created_at_organization_and_more'),
    ]

    operations = [
    ]
