# Generated by Django 5.0.3 on 2025-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_organizationmembership_home_wallpaper_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='home_wallpaper_filename',
        ),
        migrations.AddField(
            model_name='organization',
            name='home_wallpaper_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
