# Generated by Django 5.0.3 on 2025-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_remove_organizationmembership_home_wallpaper_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='home_wallpaper_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='card_covers/'),
        ),
    ]
