# Generated by Django 5.0.3 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_board_home_wallpaper_filename_card_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tag_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardattachment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
