# Generated by Django 5.0.3 on 2025-12-24 15:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_card_tag_colors_cardattachment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('handle', models.CharField(blank=True, max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números, _ ou .', regex='^[a-z0-9_\\.]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('activity', 'Atividade'), ('description', 'Descrição')], max_length=20)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions_made', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='boards.board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='boards.card')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['card', 'mentioned_user'], name='boards_ment_card_id_86d5e5_idx'), models.Index(fields=['board', 'mentioned_user'], name='boards_ment_board_i_abe85a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('card', 'mentioned_user', 'source'), name='uniq_mention_per_card_user_source'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['handle'], name='boards_user_handle_d2e525_idx'),
        ),
    ]
