# Generated by Django 5.0.3 on 2025-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_userprofile_mention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
