# Generated by Django 5.0.3 on 2025-12-27 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_userprofile_posto_userprofile_ramal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mention',
            name='uniq_mention_per_card_user_source',
        ),
        migrations.AddField(
            model_name='board',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mention',
            name='card_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='boards.cardlog'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('card', 'mentioned_user', 'source', 'card_log'), name='uniq_mention_per_card_user_source_log'),
        ),
    ]
