# Generated by Django 5.0.3 on 2025-12-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_remove_mention_uniq_mention_per_card_user_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position', 'id']},
        ),
    ]
