# Generated by Django 5.0.3 on 2025-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_alter_card_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
