# Generated by Django 5.0.3 on 2025-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_userprofile_avatar_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='due_colors',
            field=models.JSONField(blank=True, default=dict, help_text="Cores do prazo: {'ok':'#..','warn':'#..','overdue':'#..'}"),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='due_notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='due_warn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mention',
            name='due_colors',
            field=models.JSONField(blank=True, default=dict, help_text="Cores do prazo: {'ok':'#..','warn':'#..','overdue':'#..'}"),
        ),
    ]
