# Generated by Django 5.0.3 on 2026-01-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_board_due_colors_card_due_date_card_due_notify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_aggregator_column',
            field=models.BooleanField(default=False),
        ),
    ]
