# Generated by Django 5.0.3 on 2026-01-04 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_board_show_aggregator_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_favorites', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_groups', to='boards.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='boards.board')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boards.boardgroup')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='boardgroup',
            index=models.Index(fields=['user', 'organization', 'position'], name='boards_boar_user_id_db6854_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgroup',
            index=models.Index(fields=['user', 'organization', 'is_favorites'], name='boards_boar_user_id_c9770a_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgroupitem',
            index=models.Index(fields=['group', 'position'], name='boards_boar_group_i_44f94e_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgroupitem',
            index=models.Index(fields=['board'], name='boards_boar_board_i_df5e03_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardgroupitem',
            constraint=models.UniqueConstraint(fields=('group', 'board'), name='uniq_group_board'),
        ),
    ]
