# Generated by Django 5.0.3 on 2026-01-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_alter_boardgroup_name_boardactivityreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_identity_label',
            field=models.CharField(blank=True, choices=[('display_name', 'Nome amigável'), ('email', 'Email'), ('handle', 'Handle')], default='display_name', max_length=20),
        ),
    ]
