# Generated by Django 5.0.3 on 2026-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_userprofile_preferred_identity_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mention',
            name='uniq_mention_per_card_user_source_log',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='due_colors',
        ),
        migrations.AddField(
            model_name='mention',
            name='emailed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mention',
            name='seen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
