# Generated by Django 5.0.3 on 2026-01-07 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0029_remove_mention_uniq_mention_per_card_user_source_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mention',
            name='boards_ment_card_id_86d5e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='mention',
            name='boards_ment_board_i_abe85a_idx',
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('card', 'mentioned_user', 'source'), name='uniq_mention_card_user_source'),
        ),
    ]
