# Generated by Django 5.0.3 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_remove_mention_boards_ment_card_id_86d5e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_sidebar',
            field=models.BooleanField(default=False, help_text='Mostrar atividade fixa na lateral do modal do card (estilo Trello)'),
        ),
    ]
