# Generated by Django 5.0.3 on 2026-01-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_userprofile_activity_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
