# Generated by Django 5.0.3 on 2026-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_boardaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
