# Generated by Django 5.x on 2026-01-17

from django.db import migrations, models


def forward_set_all_true(apps, schema_editor):
    UserProfile = apps.get_model("boards", "UserProfile")
    UserProfile.objects.all().update(activity_sidebar=True)


def backward_noop(apps, schema_editor):
    # rollback não é desejado (decisão de produto)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0034_boardmembership_accepted_at_and_more"),
    ]


    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="activity_sidebar",
            field=models.BooleanField(
                default=True,
                help_text="Mostrar atividade fixa na lateral do modal do card (estilo Trello)",
            ),
        ),
        migrations.RunPython(forward_set_all_true, backward_noop),
    ]
