


# Generated by Django 5.0.3 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ("boards", "0036_alter_cardlog_options_cardlog_actor_cardseen"),
    ]
    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_counts",
            field=models.BooleanField(
                default=True,
                help_text="Mostrar contadores de atividade (comentários/itens) no modal do card",
            ),
        ),
    ]
