# Generated by Django 5.0.3 on 2026-02-01 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_card_archived_at_card_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['card', 'mentioned_user'], name='boards_ment_card_id_86d5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['board', 'mentioned_user'], name='boards_ment_board_i_abe85a_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['card', 'source'], name='boards_ment_card_id_a36cca_idx'),
        ),
    ]
