# Generated by Django 5.0.3 on 2026-02-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_mention_boards_ment_card_id_86d5e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='boards.cardlog'),
        ),
    ]
