# Generated by Django 5.0.3 on 2026-02-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0040_cardlog_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='content_delta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardlog',
            name='content_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
