# Generated by Django 5.0.3 on 2026-02-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0041_cardlog_content_delta_cardlog_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='board_col_width',
            field=models.PositiveSmallIntegerField(default=240),
        ),
    ]
