# Generated by Django 5.0.3 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0042_userprofile_board_col_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
