# Generated by Django 5.0.3 on 2026-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0043_board_archived_at_board_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
