# Generated by Django 5.0.3 on 2026-02-05 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_userprofile_notify_email_userprofile_notify_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_only_owned_or_mentioned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CardNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warn', 'Data aviso'), ('warn_minus_1', 'Véspera do aviso'), ('due_minus_1', 'Véspera do vencimento'), ('due', 'Vencimento')], max_length=20)),
                ('run_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='boards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['run_date', 'kind'], name='boards_card_run_dat_dd9543_idx'), models.Index(fields=['card', 'kind'], name='boards_card_card_id_302b4a_idx'), models.Index(fields=['user', 'run_date'], name='boards_card_user_id_d8eade_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cardnotificationlog',
            constraint=models.UniqueConstraint(fields=('card', 'user', 'kind', 'run_date'), name='uniq_card_user_kind_rundate'),
        ),
    ]
