# Generated by Django 5.0.3 on 2026-02-08 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0046_cardfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='boards.column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['column', 'include_new'], name='boards_colu_column__a3cb3f_idx'), models.Index(fields=['user'], name='boards_colu_user_id_aa26e3_idx')],
                'unique_together': {('column', 'user')},
            },
        ),
    ]
