# Generated by Django 5.0.3 on 2026-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0047_columnfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag_catalog',
            field=models.JSONField(blank=True, default=dict, help_text='Catálogo de etiquetas do usuário, por board, com cor'),
        ),
    ]
