# Generated by Django 5.0.3 on 2026-03-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0054_social_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialpost',
            new_name='boards_soci_user_id_a11109_idx',
            old_name='boards_soci_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='socialpostseen',
            new_name='boards_soci_viewer__c05b08_idx',
            old_name='boards_soci_viewer__seen_idx',
        ),
        migrations.AddField(
            model_name='cardattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
