# Generated by Django 5.0.3 on 2026-03-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0054_social_posts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialpost',
            new_name='boards_soci_user_id_a11109_idx',
            old_name='boards_soci_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='socialpostseen',
            new_name='boards_soci_viewer__c05b08_idx',
            old_name='boards_soci_viewer__seen_idx',
        ),
    ]
