# Generated by Django 5.0.3 on 2026-03-21 23:30
# RenameIndex desnecessário: Django 5.0 já cria índices com nomes corretos.
# Mantida como no-op para preservar o grafo de dependências.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0054_social_posts'),
    ]

    operations = []
