# Generated by Django 5.0.3 on 2026-03-23 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0055_add_created_by_to_cardattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op: campo created_by já adicionado em 0055_add_created_by_to_cardattachment.
        # Mantido vazio para preservar a cadeia de dependências.
    ]
