# Generated by Django 5.0.3 on 2026-03-31 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0055_add_created_by_to_cardattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracktime_limit_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Tempo em minutos até pedir confirmação do timer. 0 = padrão do sistema (60 min).'),
        ),
        migrations.CreateModel(
            name='NotificationBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(default='', max_length=200)),
                ('event_summary', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_buffer', to='boards.card')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_buffer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sent', 'created_at'], name='boards_noti_sent_1c03a6_idx'), models.Index(fields=['card', 'recipient', 'sent'], name='boards_noti_card_id_3fed6b_idx')],
            },
        ),
    ]
