# Generated by Django 5.0.3 on 2026-03-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0057_notification_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_fri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_mon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_thu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_tue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_days_wed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_end_time',
            field=models.TimeField(default='17:00', help_text='Hora de fim para receber notificações.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_offhours_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_offhours_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_start_time',
            field=models.TimeField(default='08:00', help_text='Hora de início para receber notificações.'),
        ),
    ]
