# Generated by Django 5.0.3 on 2026-03-31 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0058_add_notification_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fixed_posto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_posto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_ramal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_setor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_telefone',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(blank=True, choices=[('excited', 'Animado'), ('happy', 'Bem'), ('calm', 'Tranquilo'), ('neutral', 'Normal'), ('tired', 'Cansado'), ('stressed', 'Estressado'), ('sick', 'Indisposto')], default='', max_length=20)),
                ('mood_note', models.CharField(blank=True, default='', max_length=300)),
                ('lunch_text', models.CharField(blank=True, default='', max_length=200)),
                ('lunch_photo', models.ImageField(blank=True, null=True, upload_to='social/lunch/')),
                ('daily_posto', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='boards_dail_user_id_3139f7_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
