# Generated by Django 5.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0059_social_v2_checkin_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/videos/'),
        ),
    ]
