# Generated by Django 5.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0061_social_reactions_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamilaKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(
                    choices=[
                        ('about', 'Sobre a CAMIM'),
                        ('services', 'Serviços e Produtos'),
                        ('rules', 'Regras e Políticas'),
                        ('processes', 'Processos Internos'),
                        ('faq', 'Perguntas Frequentes'),
                        ('contacts', 'Contatos e Endereços'),
                        ('culture', 'Cultura e Valores'),
                        ('other', 'Outros'),
                    ],
                    default='about',
                    max_length=20,
                )),
                ('content', models.TextField(help_text='Conteúdo que a Camila deve saber')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Camila — Conhecimento',
                'verbose_name_plural': 'Camila — Base de Conhecimento',
                'ordering': ['category', 'title'],
            },
        ),
    ]
