# Generated by Django 5.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0062_camilaknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamilaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_react', models.TextField(verbose_name='Prompt — Reação a ações')),
                ('prompt_chat', models.TextField(verbose_name='Prompt — Chat conversacional')),
                ('prompt_coach', models.TextField(verbose_name='Prompt — Camilo (coach)')),
                ('model', models.CharField(
                    choices=[
                        ('llama-3.3-70b-versatile', 'Llama 3.3 70B (padrão)'),
                        ('llama-3.1-8b-instant', 'Llama 3.1 8B (rápido)'),
                        ('llama3-70b-8192', 'Llama 3 70B'),
                        ('llama3-8b-8192', 'Llama 3 8B'),
                        ('mixtral-8x7b-32768', 'Mixtral 8x7B'),
                        ('gemma2-9b-it', 'Gemma 2 9B'),
                    ],
                    default='llama-3.3-70b-versatile',
                    max_length=60,
                )),
                ('temperature', models.FloatField(default=0.8)),
                ('max_tokens', models.IntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camila — Configuração',
                'verbose_name_plural': 'Camila — Configuração',
            },
        ),
    ]
