# Generated by Django 5.0.3 on 2026-03-31 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0068_socialcarddismiss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='visibility',
            field=models.CharField(choices=[('all', 'Todos'), ('friends', 'Apenas amigos')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='socialpostcomment',
            name='reply_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialpostcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='boards.socialpostcomment'),
        ),
        migrations.AlterField(
            model_name='camilaconfig',
            name='model',
            field=models.CharField(choices=[('openai/gpt-oss-20b', 'GPT-OSS 20B (rápido)'), ('openai/gpt-oss-120b', 'GPT-OSS 120B (potente)'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B'), ('llama-3.1-8b-instant', 'Llama 3.1 8B'), ('llama3-70b-8192', 'Llama 3 70B'), ('mixtral-8x7b-32768', 'Mixtral 8x7B')], default='openai/gpt-oss-20b', max_length=60),
        ),
        migrations.AlterField(
            model_name='camilaconfig',
            name='prompt_chat',
            field=models.TextField(default='Você é Camila, a IA simpática e inteligente da rede social de trabalho da CAMIM. Você é uma assistente conversacional. Os colaboradores podem falar com você sobre qualquer assunto: trabalho, dúvidas, desabafos, ideias, piadas, curiosidades, dicas de produtividade, etc. Seja calorosa, divertida, use emojis com moderação e mantenha um tom profissional mas descontraído. Respostas curtas e diretas (máx 3 parágrafos). Se perceber sofrimento intenso, sugira buscar apoio profissional. Português brasileiro. Nunca diagnostique doenças. Use a base de conhecimento abaixo para responder perguntas sobre a CAMIM quando relevante. Se não souber, diga que não tem essa informação ainda.', verbose_name='Prompt — Chat conversacional'),
        ),
        migrations.AlterField(
            model_name='camilaconfig',
            name='prompt_coach',
            field=models.TextField(default='Você é Camilo, um coach de bem-estar gentil e prático. Seu foco é motivação, hábitos saudáveis e saúde mental. Converse de forma leve, positiva e acolhedora. Nunca diagnostique doenças. Se perceber sofrimento intenso, sugira buscar apoio profissional. Respostas curtas e diretas (máximo 3 parágrafos). Português brasileiro.', verbose_name='Prompt — Camilo (coach)'),
        ),
        migrations.AlterField(
            model_name='camilaconfig',
            name='prompt_react',
            field=models.TextField(default='Você é Camila, a IA simpática da rede social de trabalho da CAMIM. O colega acabou de compartilhar algo na rede. Faça um comentário CURTO (1-2 frases no máximo), divertido, engajador e caloroso. Use emojis. Se ele falou o que vai almoçar, comente sobre a comida de forma descontraída. Se falou o humor, acolha. Se postou algo, incentive. Seja leve, profissional e NUNCA chata. Português brasileiro.', verbose_name='Prompt — Reação a ações'),
        ),
        migrations.CreateModel(
            name='CamilaPOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Setor/Categoria')),
                ('pdf_file', models.FileField(upload_to='camila/pops/')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='Texto completo extraído do PDF')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Resumo inteligente (IA)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camila — POP',
                'verbose_name_plural': 'Camila — POPs',
                'ordering': ['category', 'code', 'title'],
            },
        ),
    ]
