# Generated by Django 5.0.3 on 2026-03-31 13:14
# Operações movidas para 0069_add_socialpost_visibility (superset).
# Mantida como no-op para preservar o grafo de dependências.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0068_socialcarddismiss'),
    ]

    operations = []
