# Generated by Django 5.0.3 on 2026-03-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0068_socialcarddismiss'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostcomment',
            name='reply_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialpostcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='boards.socialpostcomment'),
        ),
    ]
