# Generated by Django 5.0.3 on 2026-03-31 15:14
# CamilaPOP já criada em 0069_add_socialpost_visibility (superset).
# Mantida como no-op para preservar o grafo de dependências.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0069_socialpostcomment_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
