# Generated by Django 5.0.3 on 2026-03-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0070_camila_pop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camilapop',
            options={'ordering': ['category', 'code', 'title'], 'verbose_name': 'Camila — POP', 'verbose_name_plural': 'Camila — POPs'},
        ),
        migrations.AddField(
            model_name='camilapop',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Setor/Categoria'),
        ),
    ]
