# Generated by Django 5.0.3 on 2026-03-31 15:39
# category já incluída no CreateModel de 0069_add_socialpost_visibility.
# Mantida como no-op para preservar o grafo de dependências.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0070_camila_pop'),
    ]

    operations = []
