# Generated by Django 5.0.3 on 2026-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0071_retroactive_avatar_cover_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_done',
            field=models.BooleanField(default=False),
        ),
    ]
