# Generated by Django 5.0.3 on 2026-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0071_camila_pop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='camilapop',
            name='raw_text',
            field=models.TextField(blank=True, default='', verbose_name='Texto completo extraído do PDF'),
        ),
        migrations.AlterField(
            model_name='camilapop',
            name='extracted_text',
            field=models.TextField(blank=True, default='', verbose_name='Resumo inteligente (IA)'),
        ),
    ]
