# Generated by Django 5.0.3 on 2026-04-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0072_onboarding_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='boards.socialpost')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'viewer'], name='boards_soci_post_id_ca1f63_idx')],
                'unique_together': {('post', 'viewer')},
            },
        ),
    ]
