# Generated by Django 5.0.3 on 2026-04-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0072_onboarding_done'),
        ('boards', '0073_add_socialpost_visibility'),
    ]

    operations = [
    ]
