# Generated by Django 5.0.3 on 2026-04-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0073_socialpostview'),
        ('boards', '0074_merge_20260401_1229'),
    ]

    operations = [
    ]
