# Generated by Django 5.0.3 on 2026-04-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0073_socialpostview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camilaknowledge',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
