# Generated by Django 5.0.3 on 2026-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0076_increase_camila_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camilapop',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cardattachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
