# Generated by Django 5.0.3 on 2026-04-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0075_merge_0073_socialpostview_0074_merge_20260401_1229'),
        ('boards', '0087_socialpost_text_style'),
    ]

    operations = [
    ]
