# Generated by Django 5.0.3 on 2026-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0088_merge_20260403_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camilapop',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chatsticker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socialpostversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='termsacceptancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
