# Generated by Django 5.0.3 on 2026-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0094_add_storedfile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='camilanews',
            new_name='boards_cami_fetched_7bd7ae_idx',
            old_name='boards_cami_fetched_idx',
        ),
        migrations.RenameIndex(
            model_name='healthchatmessage',
            new_name='boards_heal_user_id_ace569_idx',
            old_name='boards_heal_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='socialpostview',
            new_name='boards_soci_post_id_b5a9a2_idx',
            old_name='boards_soci_post_id_source_idx',
        ),
        migrations.AlterField(
            model_name='cardmovehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood',
            field=models.CharField(blank=True, choices=[('excited', 'Animado'), ('happy', 'Bem'), ('calm', 'Tranquilo'), ('neutral', 'Normal'), ('tired', 'Cansado'), ('stressed', 'Estressado'), ('sick', 'Indisposto'), ('sad', 'Triste'), ('down', 'Desanimado'), ('anxious', 'Ansioso'), ('angry', 'Com raiva'), ('inlove', 'Apaixonado'), ('grateful', 'Grato')], default='', max_length=20),
        ),
    ]
