# Generated by Django 5.0.3 on 2026-04-14 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0096_merge_20260412_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_whatsnew_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsNewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('emoji', models.CharField(blank=True, default='✨', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='boards_what_publish_45f28c_idx'), models.Index(fields=['is_published', '-published_at'], name='boards_what_is_publ_febde9_idx')],
            },
        ),
    ]
