# Generated by Django 5.0.3 on 2026-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0100_rename_boards_cami_user_id_msg_idx_boards_cami_user_id_ba329e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='camim_sub',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador imutável do usuário no IDCamim (OAuth sub). Usado para casar o login mesmo que o email mude.', max_length=64, null=True, unique=True),
        ),
    ]
