# Generated by Django 5.0.3 on 2026-05-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0106_socialpost_video_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warn', 'Aviso'), ('post_block', 'Bloqueio do post'), ('social_block', 'Bloqueio do social (não publica/comenta)'), ('account_block', 'Bloqueio da conta NossoTrello'), ('idcamim_block', 'Bloqueio do IDCamim')], db_index=True, max_length=20)),
                ('reason', models.TextField(help_text='Texto livre que vai pro email do usuário banido.')),
                ('terms_clause', models.CharField(blank=True, default='', help_text='Cláusula dos Termos de Uso violada (ex: 4.4).', max_length=40)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('effective_until', models.DateTimeField(blank=True, help_text='Quando expira (null = permanente até revogação).', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, default='')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Punição aplicada',
                'verbose_name_plural': 'Punições aplicadas',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='BannedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Termo normalizado (minúsculas, sem acentos/separadores).', max_length=80, unique=True)),
                ('display', models.CharField(blank=True, default='', help_text='Forma humana do termo (só pra leitura no admin).', max_length=120)),
                ('severity', models.CharField(choices=[('block', 'Bloqueia (HTTP 400)'), ('flag', 'Sinaliza para revisão humana')], default='block', max_length=10)),
                ('category', models.CharField(choices=[('hate', 'Discurso de ódio'), ('sexual', 'Conteúdo sexual'), ('violence', 'Violência'), ('harassment', 'Assédio'), ('spam', 'Spam'), ('pii', 'Dados pessoais sensíveis'), ('political', 'Político/religioso/comercial externo'), ('other', 'Outro')], db_index=True, default='other', max_length=20)),
                ('terms_clause', models.CharField(blank=True, default='4.4', help_text='Cláusula dos Termos de Uso violada (ex: 4.4).', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Termo banido',
                'verbose_name_plural': 'Termos banidos',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_kind', models.CharField(choices=[('social_post', 'Post'), ('social_comment', 'Comentário'), ('chat_message', 'Mensagem de chat'), ('user_handle', 'Handle'), ('user_name', 'Nome do usuário'), ('user_bio', 'Bio')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('subject_text', models.TextField(blank=True, default='', help_text='Snapshot do texto analisado (evidência imutável).')),
                ('layer1_hit', models.BooleanField(default=False)),
                ('layer2_provider', models.CharField(blank=True, default='', max_length=40)),
                ('layer2_scores', models.JSONField(blank=True, default=dict)),
                ('layer2_flagged', models.BooleanField(default=False)),
                ('layer2_categories', models.JSONField(blank=True, default=list)),
                ('layer2_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('auto_blocked', 'Bloqueado automaticamente (Camada 1)'), ('pending_human', 'Aguardando revisão humana'), ('human_approved', 'Aprovado por moderador'), ('human_rejected', 'Rejeitado por moderador'), ('auto_cleared', 'Liberado automaticamente (Camada 2)')], db_index=True, default='pending_human', max_length=24)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caso de moderação',
                'verbose_name_plural': 'Casos de moderação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='socialpost',
            name='moderation_clause',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='moderation_reason',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='moderation_status',
            field=models.CharField(choices=[('clean', 'Liberado'), ('pending_review', 'Em análise'), ('blocked', 'Bloqueado pela política'), ('removed_by_moderator', 'Removido por moderador')], db_index=True, default='clean', max_length=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idcamim_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idcamim_blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_offense_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_block_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_blocked_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_warn_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['moderation_status', '-created_at'], name='boards_soci_moderat_183548_idx'),
        ),
        migrations.AddField(
            model_name='banlog',
            name='applied_by',
            field=models.ForeignKey(blank=True, help_text='Quem aplicou (null = sistema/automático).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_logs_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banlog',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannedterm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='layer1_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boards.bannedterm'),
        ),
        migrations.AddField(
            model_name='banlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_logs', to='boards.moderationcase'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', '-created_at'], name='boards_mode_status_037a56_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['content_kind', 'object_id'], name='boards_mode_content_f54304_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['author', '-created_at'], name='boards_mode_author__78be2e_idx'),
        ),
        migrations.AddIndex(
            model_name='banlog',
            index=models.Index(fields=['user', '-applied_at'], name='boards_banl_user_id_021867_idx'),
        ),
        migrations.AddIndex(
            model_name='banlog',
            index=models.Index(fields=['action', '-applied_at'], name='boards_banl_action_074bb0_idx'),
        ),
    ]
