# Generated by Django 5.0.3 on 2026-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0109_seed_banned_terms_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedterm',
            name='match_mode',
            field=models.CharField(choices=[('substring', 'Substring (qualquer lugar)'), ('word', 'Palavra inteira (evita falso positivo em termos curtos)')], default='substring', help_text="'substring' (padrão) casa em qualquer parte do texto. 'word' exige fronteira de palavra — use em termos curtos (cu, pau, bunda) pra evitar falso positivo em palavras normais (currículo, Paula, abundância).", max_length=10),
        ),
    ]
