# Generated by Django 5.0.3 on 2026-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0112_convert_blocks_to_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='camilinho_variant',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='mood_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
