# Generated by Django 5.0.3 on 2026-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0114_repost_interactions_to_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_tarefas_to_social',
            field=models.BooleanField(default=True),
        ),
    ]
