# Generated by Django 5.0.3 on 2026-06-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0116_cardsecret_cardsecretreveal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Apenas o domínio, sem '@'. Ex.: gp5partners.com.br", max_length=255, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', help_text='Motivo / quem pediu (opcional).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domínio de e-mail permitido',
                'verbose_name_plural': 'Domínios de e-mail permitidos',
                'ordering': ['domain'],
            },
        ),
    ]
