# Generated by Django 5.0.3 on 2026-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0118_boardemailingest'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardemailingest',
            name='protocol',
            field=models.CharField(choices=[('imap', 'IMAP'), ('pop', 'POP3')], default='imap', max_length=8),
        ),
        migrations.AddField(
            model_name='boardemailingest',
            name='seen_uids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
