# Generated by Django 5.0.3 on 2026-06-14 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0119_boardemailingest_protocol_boardemailingest_seen_uids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('enter', 'Quando um card entra na lista'), ('leave', 'Quando um card sai da lista')], max_length=10)),
                ('action', models.CharField(choices=[('send_email', 'Disparar e-mail avisando alguém'), ('move_to', 'Mover o card para outra coluna'), ('set_due', 'Definir data de entrega (+N dias)'), ('add_label', 'Adicionar etiqueta'), ('mark_delivered', 'Marcar como entregue')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='boards.column')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_automations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
