# Generated by Django 5.0.3 on 2026-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0121_alter_columnautomation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='autosort_dir',
            field=models.CharField(choices=[('asc', 'Crescente'), ('desc', 'Decrescente')], default='asc', max_length=4),
        ),
        migrations.AddField(
            model_name='column',
            name='autosort_field',
            field=models.CharField(choices=[('due', 'Data de entrega'), ('start', 'Data de início'), ('created', 'Data de criação'), ('title', 'Nome (A→Z)')], default='due', max_length=10),
        ),
        migrations.AddField(
            model_name='column',
            name='autosort_freq',
            field=models.CharField(choices=[('none', 'Não ordenar automaticamente'), ('daily', 'Todo dia'), ('weekly', 'Toda semana')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='column',
            name='autosort_last_run',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='autosort_weekday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
