# Generated by Django 5.0.3 on 2026-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0122_column_autosort_dir_column_autosort_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
