# Generated by Django 5.0.3 on 2026-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0123_board_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cover_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
