# Generated by Django 5.0.3 on 2026-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0124_card_cover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnautomation',
            name='armed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='columnautomation',
            name='trigger',
            field=models.CharField(choices=[('enter', 'Quando um card entra na lista'), ('leave', 'Quando um card sai da lista'), ('count_below', 'Quando a lista fica com MENOS de X cards'), ('count_above', 'Quando a lista fica com MAIS de X cards')], max_length=16),
        ),
    ]
