# Generated by Django 5.0.3 on 2026-06-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0125_columnautomation_armed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnautomation',
            name='action',
            field=models.CharField(choices=[('send_email', 'Disparar e-mail avisando alguém'), ('send_whatsapp', 'Enviar mensagem no WhatsApp'), ('assign_user', 'Marcar uma pessoa (cria acompanhamento)'), ('move_to', 'Mover o card para outra coluna'), ('copy_to', 'Copiar o card para outra coluna'), ('set_due', 'Definir data de entrega (+N dias)'), ('set_start', 'Definir data de início (+N dias)'), ('add_label', 'Adicionar etiqueta'), ('mark_delivered', 'Marcar como entregue')], max_length=20),
        ),
    ]
