# Generated by Django 5.0.3 on 2026-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0126_alter_columnautomation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='column_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnautomation',
            name='trigger',
            field=models.CharField(choices=[('enter', 'Quando um card entra na lista'), ('leave', 'Quando um card sai da lista'), ('count_below', 'Quando a lista fica com MENOS de X cards'), ('count_above', 'Quando a lista fica com MAIS de X cards'), ('stale', 'Quando um card fica parado X dias nesta lista')], max_length=16),
        ),
    ]
