# Generated by Django 5.0.3 on 2026-06-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0127_card_column_since_alter_columnautomation_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='autosort_hour',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='column',
            name='autosort_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
