# Generated by Django 5.0.3 on 2026-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0128_column_autosort_hour_column_autosort_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='counter_days',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='card',
            name='counter_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
