# Generated by Django 5.0.3 on 2026-06-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0130_userprofile_code_block_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='column_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='columnautomation',
            name='action',
            field=models.CharField(choices=[('send_email', 'Disparar e-mail avisando alguém'), ('send_whatsapp', 'Enviar mensagem no WhatsApp'), ('notify_placer', 'Avisar quem colocou o card aqui (WhatsApp/e-mail)'), ('assign_user', 'Marcar uma pessoa (cria acompanhamento)'), ('move_to', 'Mover o card para outra coluna'), ('copy_to', 'Copiar o card para outra coluna'), ('set_due', 'Definir data de entrega (+N dias)'), ('set_start', 'Definir data de início (+N dias)'), ('add_label', 'Adicionar etiqueta'), ('mark_delivered', 'Marcar como entregue')], max_length=20),
        ),
    ]
