# Generated by Django 5.0.3 on 2026-07-17 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0131_card_column_entered_by_alter_columnautomation_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('declined', 'Recusada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='boards.board')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='boardownershiptransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('board',), name='uniq_pending_ownership_transfer_per_board'),
        ),
    ]
