# Generated by Django 5.0.3 on 2026-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0132_boardownershiptransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_modal_theme',
            field=models.CharField(choices=[('glass', 'Claro'), ('dark', 'Escuro')], default='glass', help_text='Tema do modal do card (claro/escuro). Vale para todos os cards do usuário.', max_length=10),
        ),
    ]
