# Generated by Django 5.0.3 on 2026-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0135_card_is_impeded_cardimpediment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cover_prev_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
