# Generated by Django 5.0.3 on 2026-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0136_card_cover_prev_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(),
        ),
    ]
