# Generated by Django 5.0.3 on 2026-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0137_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='camim_picture_url',
            field=models.URLField(blank=True, default='', help_text="Foto de perfil do IDCamim (claim 'picture'). Fallback quando não há avatar próprio, com prioridade sobre o preset.", max_length=500),
        ),
    ]
