# Generated by Django 5.0.3 on 2026-07-27 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0138_userprofile_camim_picture_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardattachment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='cardattachment',
            index=models.Index(fields=['card', 'is_active', 'created_at'], name='cardattach_card_active_idx'),
        ),
    ]
