# Generated by Django 5.0.3 on 2026-08-04 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0139_cardattachment_softdelete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('member', 'Membro')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialGroupScrapbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='social/groups/scrapbook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='socialpost',
            name='show_on_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups_onboarding_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('theme', models.CharField(blank=True, default='', max_length=120)),
                ('interests', models.TextField(blank=True, default='')),
                ('vibe', models.CharField(blank=True, default='', max_length=120)),
                ('goal', models.CharField(blank=True, default='', max_length=200)),
                ('cover_svg', models.TextField(blank=True, default='')),
                ('star_score', models.PositiveSmallIntegerField(default=0)),
                ('last_publication_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_social_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='socialpost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.socialgroup'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['group', '-created_at'], name='boards_soci_group_i_e8d460_idx'),
        ),
        migrations.AddField(
            model_name='socialgroupchatmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='boards.socialgroup'),
        ),
        migrations.AddField(
            model_name='socialgroupchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_group_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='boards.socialgroup'),
        ),
        migrations.AddField(
            model_name='socialgroupmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_group_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialgroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialgroupscrapbookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_group_scrapbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialgroupscrapbookentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapbook_entries', to='boards.socialgroup'),
        ),
        migrations.AddIndex(
            model_name='socialgroup',
            index=models.Index(fields=['slug'], name='boards_soci_slug_e10f24_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgroup',
            index=models.Index(fields=['-updated_at'], name='boards_soci_updated_3023b6_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgroupchatmessage',
            index=models.Index(fields=['group', 'created_at'], name='boards_soci_group_i_bcc59c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialgroupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='socialgroupscrapbookentry',
            index=models.Index(fields=['group', '-created_at'], name='boards_soci_group_i_4cd1c2_idx'),
        ),
    ]
