# Generated by Django 5.0.3 on 2026-08-04 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0140_socialgroupchatmessage_socialgroupmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialgroupmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gestor'), ('member', 'Membro')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='SocialGroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='boards.socialgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
