# Generated by Django 5.2.17 on 2026-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0145_socialgroup_wallpaper_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroupscrapbookentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/groups/scrapbook/'),
        ),
    ]
