# Generated by Django 5.2.17 on 2026-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0146_scrapbook_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroup',
            name='theme_gallery_hint',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
