# Generated by Django 5.2.17 on 2026-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0147_group_theme_gallery_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroup',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
