# Generated by Django 5.2.17 on 2026-08-06 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0148_socialgroup_is_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_logs', to='boards.board'),
        ),
        migrations.AddField(
            model_name='cardlog',
            name='board_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_logs_received', to='boards.board'),
        ),
        migrations.AddIndex(
            model_name='cardlog',
            index=models.Index(fields=['board', 'created_at'], name='cardlog_board_created_idx'),
        ),
    ]
