# Generated by Django 5.2.17 on 2026-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0149_cardlog_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattachment',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
