# Generated by Django 5.2.17 on 2026-09-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0150_cardattachment_is_active_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnautomation',
            name='action',
            field=models.CharField(choices=[('send_email', 'Disparar e-mail avisando alguém'), ('send_whatsapp', 'Enviar mensagem no WhatsApp'), ('notify_placer', 'Avisar quem colocou o card aqui (WhatsApp/e-mail)'), ('assign_user', 'Marcar uma pessoa (cria acompanhamento)'), ('move_to', 'Mover o card para outra coluna'), ('copy_to', 'Copiar o card para outra coluna'), ('set_due', 'Definir data de entrega (+N dias)'), ('set_start', 'Definir data de início (+N dias)'), ('add_label', 'Adicionar etiqueta'), ('mark_delivered', 'Marcar como entregue'), ('mark_undelivered', 'Marcar como NÃO entregue (limpa a data de entrega)'), ('monthly_report', 'Entrega mensal de relatório (recorrência)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='columnautomation',
            name='trigger',
            field=models.CharField(choices=[('enter', 'Quando um card entra na lista'), ('leave', 'Quando um card sai da lista'), ('count_below', 'Quando a lista fica com MENOS de X cards'), ('count_above', 'Quando a lista fica com MAIS de X cards'), ('stale', 'Quando um card fica parado X dias nesta lista'), ('attach', 'Quando um anexo é adicionado a um card desta lista')], max_length=16),
        ),
        migrations.CreateModel(
            name='MonthlyReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primeiro dia do mês do ciclo (YYYY-MM-01)')),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('validating', 'Validando'), ('delivered', 'Entregue'), ('rejected', 'Anexo reprovado'), ('skipped', 'Sem anexo (histórico)')], default='pending', max_length=12)),
                ('extra_attachment_ids', models.JSONField(blank=True, default=list)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('ai_status', models.CharField(choices=[('off', 'Desligada'), ('pending', 'Aguardando'), ('done', 'Concluída'), ('error', 'Erro'), ('skipped', 'Não aplicável')], default='off', max_length=12)),
                ('ai_verdict', models.CharField(blank=True, default='', max_length=12)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_problems', models.JSONField(blank=True, default=list)),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ai_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_entries_accepted', to=settings.AUTH_USER_MODEL)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_entries_attached', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_entries', to='boards.cardattachment')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_entries', to='boards.card')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_entries', to='boards.columnautomation')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['status', 'due_on'], name='monthlyreport_status_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('card', 'month'), name='monthlyreport_card_month_uniq')],
            },
        ),
    ]
