# Generated by Django 5.2.17 on 2026-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0151_monthly_report'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['original_name'], name='storedfile_origname_idx'),
        ),
    ]
