# Generated by Django 5.2.17 on 2026-09-29 16:58

from django.db import migrations, models

# IDs da Groq gravados na config da Camila → IDs da OpenRouter.
_MAPA = {
    "llama-3.3-70b-versatile": "meta-llama/llama-3.3-70b-instruct",
    "llama-3.1-8b-instant": "meta-llama/llama-3.1-8b-instruct",
    "llama3-70b-8192": "meta-llama/llama-3.3-70b-instruct",
    "mixtral-8x7b-32768": "meta-llama/llama-3.3-70b-instruct",
}


def converter_ids(apps, schema_editor):
    CamilaConfig = apps.get_model("boards", "CamilaConfig")
    for antigo, novo in _MAPA.items():
        CamilaConfig.objects.filter(model=antigo).update(model=novo)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0152_storedfile_storedfile_origname_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camilaconfig',
            name='model',
            field=models.CharField(choices=[('openai/gpt-oss-20b', 'GPT-OSS 20B (rápido)'), ('openai/gpt-oss-120b', 'GPT-OSS 120B (potente)'), ('meta-llama/llama-3.3-70b-instruct', 'Llama 3.3 70B'), ('meta-llama/llama-3.1-8b-instruct', 'Llama 3.1 8B')], default='openai/gpt-oss-20b', max_length=60),
        ),
        migrations.RunPython(converter_ids, migrations.RunPython.noop),
    ]
